<?php
// +----------------------------------------------------------------------
// | 鸣鹤CMS [ New Better  ]
// +----------------------------------------------------------------------
// | Copyright (c) 2006~2017 http://www.mhcms.net All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( 您必须获取授权才能进行使用 )
// +----------------------------------------------------------------------
// | Author: new better <1620298436@qq.com>
// +----------------------------------------------------------------------
namespace app\house\controller;

use app\common\controller\HomeBase;
use app\common\controller\ModuleBase;
use app\common\model\Models;
use app\common\util\Money;
use app\common\util\Point;
use app\core\util\ContentTag;
use think\Cookie;
use think\Db;

class Agent extends HouseUserBase
{

    /** @var  $house_agent \think\db\Query | Models */
    private $house_agent = "house_agent";

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->view->content_model_id = $this->house_agent;
        $this->house_agent = set_model($this->house_agent);
    }

    public function index()
    {
        $this->view->lists = $this->house_agent->where(['site_id' => $this->site_id])->order('id desc')->paginate();

        return $this->view->fetch();
    }

    public function detail($user_id)
    {
        global $_W;
        $where['user_id'] = $user_id;
        $test = $this->house_agent->where($where)->find();
        $this->view->detail = $test;
        if (!$test) {
            $this->message("对不起，经纪人不存在 ！");
        }
        $this->view->detail = $test;
        $this->mapping = array_merge($this->mapping , $test);
        $this->view->seo = $this->seo($this->mapping);
        return $this->view->fetch();
    }

    public function apply()
    {
        global $_W, $_GPC;


        if (!$this->user_id) {
            Cookie::set('forward', $_W['current_url']);
            $this->message("对不起，此功能需要您登录 ！", 1, '/sso/passport/login');
        }
        $where['user_id'] = $this->user_id;
        $test = $this->house_agent->where($where)->find();


        if ($this->isPost()) {

            Db::startTrans();
            $base_info = input('post.data/a');
            $spend_top = true;
            foreach ($_W['module_config']['agent_reg_set'] as $k => $set) {
                if ($k == $_GPC['set_index']) {
                    //top expire top_expire
                    $base_info['expire'] = date("Y-m-d H:i:s", SYS_TIME + 86400 * $set['days']);

                    if ($set['money'] > 0) {
                        if ($set['unit_type'] == "balance") {
                            $spend_top = Money::spend($this->user, $set['money'], 0, "升级经纪人VIP");
                        } else {
                            $spend_top = Point::spend($this->user, $set['money'], 0, "升级经纪人VIP");
                        }
                    } else {
                        $spend_top = true;
                    }

                    if (!$spend_top) {
                        $spend_top_msg = '失败 您' . $_W['site']['config']['trade'][$set['unit_type'] . '_text'] . '不足';
                    }
                    break;
                }
            }
            if ($this->module_config['check_agent']) {
                $base_info['status'] = 1;
                $msg = "请等待审核";
            } else {
                $base_info['status'] = 99;
                $msg = "系统已经自动通过审核！";
            }
            $base_info['type'] = 1;
            $base_info['user_id'] = $this->user_id;

            if (!$test) {
                $res = $this->house_agent->model_info->add_content($base_info);
            } else {
                $res = $this->house_agent->model_info->edit_content($base_info, $where);
            }

            $url = url('house/index/index');
            if ($res['code'] == 1 && $spend_top) {
                token();
                Db::commit();
                $this->zbn_msg("申请成功， $msg ！", "1", '', 2000, "'$url'");
            } else {
                Db::rollback();
                $this->zbn_msg("申请失败 ！" . $res['msg'] . $spend_top_msg);
            }


        } else {

            if ($test && $test['status'] != 2) {
                $this->message("对不起，您已经是经纪人或者您的申请正在审核中！", 1, '/house');
            }


            $this->view->field_list = $this->house_agent->model_info->get_user_publish_fields($test);
            return $this->view->fetch();
        }
    }
}