<?php
// +----------------------------------------------------------------------
// | 鸣鹤CMS [ New Better  ]
// +----------------------------------------------------------------------
// | Copyright (c) 2006~2017 http://www.mhcms.net All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( 您必须获取授权才能进行使用 )
// +----------------------------------------------------------------------
// | Author: new better <1620298436@qq.com>
// +----------------------------------------------------------------------
namespace app\house\controller;

use app\common\controller\HomeBase;
use app\common\model\Hits;
use app\common\model\Models;
use app\core\util\ContentTag;
use app\sms\model\Notice;
use think\Db;

class Check extends HouseUserBase
{
    private $default_model_id = "house_esf";

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        //todo check access author
    }

    public static function check_admin()
    {
        global $_W, $_GPC;
        $admins = [];
        $admins[] = $_W['site']['config']['admin_openid'];

        $admins = array_merge($admins, explode(",", $_W['module_config']['admin_openid']));
        return in_array($_W['openid'], $admins);
    }


    public function index($model_id = "")
    {
        global $_W;
        if (!$model_id) {
            $model_id = $this->default_model_id;

            $this->view->controller = "esf";
        } else {
            $this->view->controller = "$model_id";
            $model_id = "house_" . $model_id;
        }
        $model = set_model($model_id);
        $this->view->model_info = $model->model_info;

        $where = [];
        $where['site_id'] = $_W['site']['id'];
        $where['status'] = ['IN', '0,1'];
        $this->view->lists = $model->where($where)->select();
        return $this->view->fetch();
    }

    public function pass()
    {

        global $_W, $_GPC;
        $query = $_GPC['query'];
        if (!is_array($query)) {
            $query = mhcms_json_decode($query);
        }

        $detail = set_model($query['model_id'])->where(['id' => $query['id'], 'site_id' => $_W['site']['id']])->find();

        $admins = [];
        $admins[] = $_W['site']['config']['admin_openid'];

        $admins = array_merge($admins, explode(",", $_W['module_config']['admin_openid']));

        if ($detail && self::check_admin()) {
            $update['status'] = 99;
            set_model($query['model_id'])->where(['id' => $query['id']])->update($update);
            $wechat_fans = $_W['wechat_fans_model']->where(['user_id' => $detail['user_id']])->find();
            $res = false;
            if ($wechat_fans) {
                $ret['msg'] = "操作完成";
                $tpl_config = mhcms_json_decode($_W['tpl_config']);
                unset($tpl_config['miniprogram']);
                $params['header'] = "您的信息已经通过管理员审核，" . $detail['title'];
                $params['header'] = "点击查看详情";
                $tpl_config['tp_url'] = url('house/user/index'  , [] , true, true);
                $res = Notice::send('系统通知', 'wxmsg', $wechat_fans['openid'], $params, $tpl_config);
            }


            if ($res) {
                $msg = "操作成功 ， 用户通知成功";
            } else {
                $msg = "操作成功 ， 用户通知失败,非微信用户";
            }
            $ret['msg'] = $msg;
        } else {
            $ret['msg'] = "对不起，您没有权限操作";
        }


        $ret['code'] = 1;

        $ret['javascript'] = "reload_page()";
        echo json_encode($ret);
    }


    public function delete()
    {
        global $_W, $_GPC;
        $query = $_GPC['query'];
        if (!is_array($query)) {
            $query = mhcms_json_decode($query);
        }

        $detail = set_model($query['model_id'])->where(['id' => $query['id'], 'site_id' => $_W['site']['id']])->find();

        if ($detail && self::check_admin()) {
            set_model($query['model_id'])->where(['id' => $query['id'], 'site_id' => $_W['site']['id']])->delete();
        }

        $ret['code'] = 1;
        $ret['msg'] = "操作成功";


        $ret['javascript'] = "reload_page()";


        echo json_encode($ret);
    }
}