<?php
// +----------------------------------------------------------------------
// | 鸣鹤CMS [ New Better  ]
// +----------------------------------------------------------------------
// | Copyright (c) 2006~2017 http://www.mhcms.net All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( 您必须获取授权才能进行使用 )
// +----------------------------------------------------------------------
// | Author: new better <1620298436@qq.com>
// +----------------------------------------------------------------------
namespace app\house\controller;

use app\common\controller\HomeBase;
use app\common\model\Models;
use app\core\util\ContentTag;
use app\core\util\MhcmsMenu;

class EmployeeOrders extends HouseUserBase
{
    private $house_appointment = "house_appointment";
    private $house_appointment_log = "house_appointment_log";

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        if (!$this->agent || $this->agent['type'] != 2) {
            $this->error("对不起，您没有权限访问该功能！");
        }
    }

    public function index($status = 0)
    {

        $where = [];
        $where['employee_id'] = $this->agent['id'];
        if ($status) {
            $where['status'] = $status;
        }
        $this->view->appointments = set_model($this->house_appointment)->where($where)->paginate();
        $this->view->status = $status;
        return $this->view->fetch();
    }


    public function set_status($id , $status){
        global $_W, $_GPC;

        $where = [];
        $where['id'] = $id;
        $where['employee_id'] = $this->agent['id'];
        $model = set_model($this->house_appointment);
        $detail = $model->where($where)->find();

        if($detail){
            //todo
            $update = [];
            $update['status'] = $status;
            $model->where($where)->update($update);

            $log_model = set_model($this->house_appointment_log);
            /** @var Models $log_model_info */
            $log_model_info = $log_model->model_info;

            $base_info['task_id'] = $id;
            $base_info['employee_id'] = $this->agent['id'];
            $base_info['operator_uid']= $this->user['id'];
            $base_info['appointment_id']= $id;
            $base_info['status'] = $status;
            $base_info['content'] = "内部经纪人更改了 订单状态";

            $res = $log_model_info->add_content($base_info);


            $ret['code'] = 1;
            $ret['msg'] = "操作成功";
            return $ret;
        }
    }
    public function detail($id)
    {
        global $_W, $_GPC;
        $where = [];
        $where['id'] = $id;
        $where['employee_id'] = $this->agent['id'];
        $model = set_model($this->house_appointment);
        $detail = $model->field('id')->where($where)->find();

        if($detail){
            $detail = Models::get_item($detail['id'] , $this->house_appointment);
        }

        $this->view->detail = $detail;
        $this->view->logs = set_model('house_appointment_log')->where(['appointment_id' => $id])->order('id desc')->select();
        return $this->view->fetch();
    }

    public function add_log($id)
    {
        global $_W, $_GPC;
        $log_model = set_model($this->house_appointment_log);
        /** @var Models $log_model_info */
        $log_model_info = $log_model->model_info;

        $model = set_model($this->house_appointment);
        /** @var Models $model_info */
        $model_info = $model->model_info;
        $where['id'] = $id;
        $where['site_id'] = $_W['site']['id'];
        $where['employee_id'] = $this->user['id'];
        $detail = Models::get_item($id, $this->house_appointment);


        if ($detail['old_data']['employee_id'] != $this->agent['id']) {
            $this->message('对不起 , 您无权访问');
        }

        if ($this->isPost()) {
            if (isset($_GPC['_form_manual'])) {
                //手动处理数据
                $base_info = $_GPC;
            } else {
                //自动获取data分组数据
                $base_info = input('post.data/a');//get the base info
            }
            $base_info['task_id'] = $id;
            $base_info['employee_id'] = $this->agent['id'];
            $base_info['operator_uid']= $this->user['id'];
            $base_info['appointment_id']= $id;

            $res = $log_model_info->add_content($base_info);
            if ($res['code'] == 1) {
                //todo update status
                if($detail['old_data']['status'] == 2){

                    $this->set_status($id , 3);
                }
                $url = url('gov_task/employee_orders/index' );
                return $this->zbn_msg($res['msg'], 1, 'true', 1000, "'$url'", "''");
            } else {
                return $this->zbn_msg($res['msg'], 2);
            }
        } else {

            $this->view->field_list = $log_model_info->get_user_publish_fields();
            return $this->view->fetch();
        }
    }
}