<?php
// +----------------------------------------------------------------------
// | 鸣鹤CMS [ New Better  ]
// +----------------------------------------------------------------------
// | Copyright (c) 2006~2017 http://www.mhcms.net All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( 您必须获取授权才能进行使用 )
// +----------------------------------------------------------------------
// | Author: new better <1620298436@qq.com>
// +----------------------------------------------------------------------
namespace app\common\controller;

use app\common\model\Roots;
use app\common\model\Sites;
use app\core\util\MhcmsDistribution;
use think\Cookie;

class FrontBase extends Base
{
    public $theme , $view_config , $uuid;

    public function _initialize()
    {
        global $_W , $_GPC;
        parent::_initialize(); // TODO: Change the autogenerated stub
        //load config
        if (isset($_W['global_config']['close_site']) && $_W['global_config']['close_site']) {
            echo $_W['global_config']['close_site_tips'];
            die();
        }
        $this->theme = $_W['theme'] = $this->global_config['theme'] ? $this->global_config['theme'] : "default";

        $this->view_config = [
            //desktop
            'front_desktop_base_layout' => APP_PATH . 'common/view/public/desktop/layout.html',
            'front_desktop_member_layout' => APP_PATH . 'common/view/public/desktop/member_layout.html',
            "desktop_header_tpl" => APP_PATH . 'common/view/public/desktop/header.html',
            "desktop_footer_tpl" => APP_PATH . 'common/view/public/desktop/footer.html',

            //mobile
            'front_mobile_base_layout' => APP_PATH . 'common/view/public/mobile/layout.html',
            'front_mobile_member_layout' => APP_PATH . 'common/view/public/mobile/member_layout.html',
            "mobile_header_tpl" => APP_PATH . 'common/view/public/mobile/header.html',
            "mobile_footer_tpl" => APP_PATH . 'common/view/public/mobile/footer.html',
        ];

        if(isset($this->site['config']['close_site']) && $this->site['config']['close_site']){
            echo($this->site['config']['close_site_tips']);
            die();
        }

        $this->is_youke = false;

        $this->uuid = Cookie::get("uuid");
        if(!$this->uuid){
            $this->uuid =  mhcms_uuid();
            Cookie::set("uuid" , $this->uuid);
        }


        //refer info stored
        if(isset($_GPC['refer']) && is_numeric($_GPC['refer'])){
            Cookie::set("refer" , $_GPC['refer']);
            $this->refer = (int) $_GPC['refer'];
        }else{
            $this->refer =(int) Cookie::get("refer");
        }
        if($this->refer){
            $_W['refer'] = $this->refer;
        }


        MhcmsDistribution::init();
    }
}