<?php

namespace app\member\controller;

use app\common\controller\UserBase;
use app\common\model\CpBet;
use app\common\model\NodeIndex;
use app\common\model\Users;
use app\common\util\forms\input;

class Lottery extends UserBase
{
    /**
     *
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->view->config([
            'view_path' => strtolower(APP_PATH . '..' . DS . 'tpl' . DS . 'lottery' . DS . MODULE_NAME . DS),
        ]);
    }

    public function index()
    {
        $this->view->seo = $this->seo($this->mapping);
        return $this->view->fetch();
    }


    public function list_bets($js = 0)
    {
        $where = ['js' => 0, 'uid' => $this->user->user_id];
        $list = CpBet::where($where)->paginate(10);
        $this->assign('list', $list);
        return $this->view->fetch();
    }

    public function history_bets()
    {

        $arr_caipiao = array(); //单式

        $week = input('param.week', 1, "intval");

        $arr_cg = array(); //串关
        $arr_ck = array(); //存款
        $arr_hk = array(); //汇款
        $arr_qk = array(); //取款

        $uid = $this->user["user_id"];
        $total = 0;
        $tytz = $cgtz = $cptz = 0;
        $tyyl = $cgyl = $cpyl = $zyl = 0;
        $zrzr = $zrzc = 0;
        $ck = $hk = $qk = 0;

//默认显示1周
        $recent_days = $week == 2 ? 13 : 6;
        $ts = 0; //退水
        $stime = date("Y-m-d 23:59:59", time()); //今天日期
        $etime = date("Y-m-d 00:00:00", strtotime("$stime -$recent_days day")); //前 $week 天日期

        $where = [];
        $where['js'] = ["EQ", 1];
        $where['uid'] = ["EQ", $uid];
        $where['addtime'] = ["between time", [$etime ,  $stime  ]];

        $list = CpBet::where($where)->order('id desc')->select();


        //$sql = "select * from c_bet where js<>0 and uid=$uid and addtime<='" . $stime . " 23:59:59' and addtime>='" . $etime . " 00:00:00' order by addtime
        foreach ($list as $rows) {
            if (!isset($arr_caipiao['tz'])) {
                $arr_caipiao['tz'] = [];
            }

            if (!isset($arr_caipiao['s'])) {
                $arr_caipiao['s'] = [];
            }
            $date_index = substr($rows['addtime'], 0, 10);
            if (!isset($arr_caipiao['tz'][$date_index])) {
                $arr_caipiao['tz'][$date_index] = 0;
            }
            $cptz += $rows['money'];


            $arr_caipiao['tz'][$date_index] += $rows['money'];
            $ts = $rows['fs'];
            if ($rows['js'] == "1" && $rows['win'] > 0) { //赢和赢一半都算赢
                $arr_caipiao['y'][$date_index] += $rows['win'] + $ts; //净赢金额不包括本金
                $zyl += $rows['win'] - $rows['money'] + $ts;
            } elseif ($rows['js'] == "1" && $rows['win'] < 0) { //输和输一半都算输
                $arr_caipiao['s'][$date_index] += abs($rows['win']) - $ts; //净输金额不包括已赢金额
            } else { //平手和无效都算取消
                $arr_caipiao['qx'][$date_index] += $rows['money'];
            }
        }


        $this->view->week = $week;
        $this->view->stime = $stime;
        $this->view->etime = $etime;
        $this->view->arr_caipiao = $arr_caipiao;
        $this->view->recent_days = $recent_days;

        return $this->view->fetch();
    }

    public function history_day()
    {
        $lm = 3;
        $date = input('param.date');
        $where['js'] = ['EQ', 1];
        $where['uid'] = ['EQ', $this->user->user_id];
        $where['bet_date'] = ['=', $date];

        $list = CpBet::where($where)->paginate(10);

        $this->view->list = $list;
        $this->view->date = $date;
        return $this->view->fetch();
    }


    public function report($this_month = 1)
    {

        $this_month = (bool) $this_month;

        $this->view->this_month = $this_month;

        if($this_month){
            $this->view->title_text = "本月报表";
            $this->view->right_title_text = "上月报表";
            $this->view->right_link = url('member/lottery/report' , ['this_month'=>0]);
            $this->view->month =  date('Y-m');
        }else{
            $this->view->title_text = "上月报表";
            $this->view->right_title_text = "本月报表";
            $this->view->right_link = url('member/lottery/report' , ['this_month'=>1]);
            $this->view->month =  date('Y-m', strtotime('-1 month'));
        }
        if (!$this->is_daili($this->user)) {
            $this->error("您没有权限访问！");
        }

        //直接下线
        $directs = Users::all(['parent_id' => $this->user->user_id]);

        foreach ($directs as $k => $direct) {
            if ($this->is_daili($direct)) {
                $direct['daili'] = 1;
                //agent
                // $agent_overview= $this->user_report_overview($direct , $this_month);
                $agent_downline_overview    = $this->down_line_overview($direct , $this_month);

                //$direct['overview'] = array_map('add_array', $agent_overview, $agent_downline_overview);
                /**
                 *

                $directs[$k]['overview'] = [
                    'win' => $direct['overview'][0] ,
                    'money' => $direct['overview'][1],
                    'bishu' => $direct['overview'][2],
                ];*/
                $directs[$k]['overview']  = $agent_downline_overview;
            } else {
                $directs[$k]['overview'] = $this->user_report_overview($direct , $this_month);
            }
        }

        $this->view->directs = $directs;
        return $this->view->fetch();
    }

    private function down_line_overview($agent, $this_month)
    {
        if ($this_month) {
            $start_time = date("Y-m-d 00:00:00");
            $stop_time = date("Y-m-d H:i:s");
        } else {
            $start_time = date('Y-m-01 00:00:00', strtotime('-1 month'));
            $stop_time = date('Y-m-t 23:59:59', strtotime('-1 month'));;
        }

        //直接下线
        $directs = Users::all(['parent_id' => $agent->user_id]);

        $ret = [
            'win' => 0 ,
            'money' => 0 ,
            'bishu' => 0
        ];

        foreach ($directs as $direct) {
            $tmp = $this->user_report_overview($direct , $this_month);
            $ret['win'] += $tmp['win'];
            $ret['money'] += $tmp['money'];
            $ret['bishu'] += $tmp['bishu'];
        }

        return $ret;
    }


    private function user_report_overview($user, $this_month)
    {
        //CP Over View
        if ($this_month) {
            $start_time = date("Y-m-01 00:00:00");
            $stop_time = date("Y-m-d H:i:s");
        } else {
            $start_time = date('Y-m-01 00:00:00', strtotime('-1 month'));
            $stop_time = date('Y-m-t 23:59:59', strtotime('-1 month'));;
        }

        $where = [
            'addtime' => ['between time', [$start_time , $stop_time]],
        ];

        $where['js'] = 1;
        $where['uid'] = $user->user_id;

        $bets = CpBet::all($where);
        $ret = [
            'win' => 0 ,
            'money' => 0 ,
            'bishu' => 0 ,
        ];
        foreach ($bets as $bet) {
            $ret['win'] += $bet['win'];
            $ret['money'] += $bet['money'];
            $ret['bishu']++;
        }
        return $ret;
    }


    public function user_bet_report($this_month){

        $user_id = input("param.user_id" , 0 , "trim,intval");

        $user = Users::get($user_id);

        if(!$user || $this->user>user_id != $user->parent_id){
            $this->error("系统出错！");
        }

        $this_month = (bool) $this_month;

        if ($this_month) {
            $start_time = date("Y-m-d 00:00:00");
            $stop_time = date("Y-m-d H:i:s");
        } else {
            $start_time = date('Y-m-01 00:00:00', strtotime('-1 month'));
            $stop_time = date('Y-m-t 23:59:59', strtotime('-1 month'));;
        }
        $where['js'] = 1;
        $where['uid'] = $user->user_id;

        $bets = CpBet::where($where)->order('id desc')->paginate(10);
        $this->view->bets = $bets;
        return $this->view->fetch();
    }

    public function is_daili($user)
    {
        $daili = 0;
        $index = NodeIndex::get(['node_type_id' => 41, 'user_id' => $user->user_id]);
        if ($index && $index['node_status'] == 1) {
            $daili = 1;
        }
        return $daili;
    }

}