<?php

// +----------------------------------------------------------------------
// | 鸣鹤CMS [ New Better  ]
// +----------------------------------------------------------------------
// | Copyright (c) 2006~2017 http://www.mhcms.net All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( 您必须获取授权才能进行使用 )
// +----------------------------------------------------------------------
// | Author: new better <1620298436@qq.com>
// +----------------------------------------------------------------------

namespace app\wechat\controller;

use app\common\controller\AdminBase;
use app\common\model\Models;
use app\common\model\SitesWechat;
use app\common\model\UserMenu;
use app\common\util\Tree2;
use app\wechat\util\MhcmsWechatEngine;
use app\wechat\util\WeiXinPlatform;
use think\Db;

class AdminFans extends AdminBase
{
    public function _initialize()
    {
        global $_W;
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->check_admin_auth($_W['account']);
        if (!$_W['account']) {
            $this->zbn_msg("对不起，未接入公众号");
        }
    }

    /**
     * @param string $group_id
     * @return string
     * @throws \Exception
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function index($group_id = "")
    {
        global $_W, $_GPC;
        $site_wechat = SitesWechat::get(['site_id' => $_W['site']['id']]);
        $where = [];
        if (!is_array($group_id) && $group_id) {
            $group_id = explode(",", $group_id);
        }
        if ($group_id) {
            foreach ($group_id as $_group_id) {
                $if[] = "%,$_group_id,%";
            }
            $where['group_ids'] = ['like', $if, 'OR']; //= ['like', ",$group_id,"];


            $query['group_id'] = join(',', $group_id);
        }

        $this->view->nickname = $nickname = $_GPC['nickname'];
        if ($nickname) {
            $where['nickname'] = ['like', "%$nickname%"];
        }
        $lists = $_W['wechat_fans_model']->where($where)->order('id desc')->paginate(null, false, ['query' => $query]);
        $this->view->lists = $lists;
        $this->view->group_ids = $group_id;
        $this->view->fans_groups = Db::name("sites_wechat_fansgroup")->where(['site_id' => $_W['site']['id']])->select()->toArray();
        return $this->view->fetch();
    }

    public function sync($page = 0)
    {
        global $_W, $_GPC;
        /*** 默认类型同步类型 */
        $account_api = MhcmsWechatEngine::create($_W['account']);
        $model = $_W['wechat_fans_model'];
        if ($page) {
            $current_page = $page;
            $data = $model->page($page)->paginate()->toArray();
            foreach ($data['data'] as $item) {
                $openids[] = $item['openid'];
            }
            $fans = $account_api->fansBatchQueryInfo($openids);

            foreach ($fans as $fan) {
                if(!$fan['openid']){
                    continue;
                }
                /**
                 * array(13) {
                 * ["subscribe"]=>
                 * int(1)
                 * ["openid"]=>
                 * string(28) "owfvCw_XzwsiId5wIuTT1Wn1dq_M"
                 * ["nickname"]=>
                 * string(24) "小黑【超腾科技】"
                 * ["sex"]=>
                 * int(1)
                 * ["language"]=>
                 * string(5) "zh_CN"
                 * ["city"]=>
                 * string(8) "Tangshan"
                 * ["province"]=>
                 * string(5) "Hebei"
                 * ["country"]=>
                 * string(5) "China"
                 * ["headimgurl"]=>
                 * string(115) "http://wx.qlogo.cn/mmopen/Q3auHgzwzM6mrXBahlnf63gAO5VCwzTG1AtmT2JVt4SnVzLJpXFSG2zuXI0UdplibpdepGqcUzRM1wMhvrTrKYQ/0"
                 * ["subscribe_time"]=>
                 * int(1505228218)
                 * ["remark"]=>
                 * string(0) ""
                 * ["groupid"]=>
                 * int(0)
                 * ["tagid_list"]=>
                 * array(0) {
                 * }
                 * }
                 */
                $new_data = [];
                $new_data['avatar'] = $fan['headimgurl'];
                $new_data['openid'] = $fan['openid'];
                $new_data['nickname'] = $fan['nickname'];
                $new_data['subscribe'] = $fan['subscribe'];
                $new_data['province'] = $fan['province'];
                $new_data['city'] = $fan['city'];
                $new_data['country'] = $fan['country'];
                $new_data['gender'] = $fan['sex'];
                $new_data['follow_time'] = date("Y-m-d H:i:s", $fan['subscribe_time']);
                $new_data['site_id'] = $_W['site']['id'];
                if (count($fan['tagid_list'])) {
                    $new_data['group_ids'] = "," . join(',', $fan['tagid_list']) . ",";;
                }

                $test_fan = $model->where(['openid' => $fan['openid']])->find();
                if (!$test_fan) {
                    if ($fan['nickname']) {
                        $model->insert($new_data);
                    }

                } else {
                    if ($fan['nickname']) {
                        $model->where(['openid' => $fan['openid']])->update($new_data);
                    }

                    if ($fan['subscribe'] == 0   && $test_fan['user_id'] == 0) {
                        $model->where(['openid' => $fan['openid']])->delete();
                    }
                }
            }
            $next_url = $data['last_page'] > $page ? url('wechat/admin_fans/sync', ['user_menu_id' => $this->menu_id, 'page' => ++$page]) : "";
            return ['next_url' => $next_url, "percent" => $current_page / $data['last_page'] * 100];
        } else {
            $this->view->fans_down_load_api = url('wechat/admin_service/download_fans');
            $this->view->fans_sync_api = url('wechat/admin_fans/sync', ['page' => 1, 'user_menu_id' => $this->menu_id]);
            return $this->view->fetch();
        }
    }

}