<?php

// +----------------------------------------------------------------------
// | 鸣鹤CMS [ New Better  ]
// +----------------------------------------------------------------------
// | Copyright (c) 2006~2017 http://www.mhcms.net All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( 您必须获取授权才能进行使用 )
// +----------------------------------------------------------------------
// | Author: new better <1620298436@qq.com>
// +----------------------------------------------------------------------

namespace app\wechat\controller;

use app\common\controller\AdminBase;
use app\common\model\Models;
use app\common\model\SitesWechat;
use app\common\model\UserMenu;
use app\common\util\Tree2;
use app\wechat\util\MhcmsWechatEngine;
use app\wechat\util\WeiXinPlatform;
use think\Db;

class AdminFansGroup extends AdminBase
{

    public $sites_wechat_fans_group = "sites_wechat_fansgroup";
    public function _initialize()
    {
        global $_W;
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->check_admin_auth($_W['account']);
    }
    public function index(){
        global $_W;
        $model = set_model($this->sites_wechat_fans_group);
        /** @var Models $model_info */
        $model_info = $model->model_info;

        $where = [];
        $where['site_id'] = $_W['site']['id'];
        $this->view->lists =  $lists = $model->where($where)->order("id desc")->paginate();
        $this->view->field_list = $model_info->get_admin_column_fields();
        $this->view->content_model_id = $this->sites_wechat_fans_group;

        $account_api = MhcmsWechatEngine::create($_W['account']);
        if (!$account_api->isTagSupported()) {

            test(false);
        }else{

            $tag_ids = [];
            $tags = $account_api->fansTagFetchAll();

            foreach($tags['tags'] as $tag){
                $where = [];
                $where['wechat_tag_id'] = $tag['id'];
                $where['sites_wechat_id'] = $_W['account']['id'];
                $where['site_id'] = $_W['site']['id'];
                $test = $model->where($where)->find();
                if(!$test){
                    $where['group_name'] = $tag['name'];
                    $model->insert($where);
                }
                $tag_ids[] = $tag['id'];
            }

            if($tag_ids){
                foreach($lists as $k=>$item){
                    if(!$item['wechat_tag_id'] || array_search($item['wechat_tag_id'] , $tag_ids)===false){
                        $model->where(['id'=>$item['id']])->delete();
                        unset($lists[$k]);
                    }
                }
            }

        }
        $this->view->lists =  $lists;
        return $this->view->fetch();
    }

    public function add(){
        global $_W, $_GPC;
        $model = set_model($this->sites_wechat_fans_group);

        /** @var Models $model_info */
        $model_info = $model->model_info;
        if ($this->isPost()) {
            if (isset($_GPC['_form_manual'])) {
                //手动处理数据
                $base_info = $_GPC;
            } else {
                //自动获取data分组数据
                $base_info = input('post.data/a');//get the base info
            }
            $base_info['sites_wechat_id'] = $_W['account']['id'];

            $account_api = MhcmsWechatEngine::create($_W['account']);
            $result = $account_api->fansTagAdd($base_info['group_name']);

            if(!is_error($result) && $result['tag']["id"]){
                $base_info['wechat_tag_id'] = $result['tag']["id"];
                $res = $model_info->add_content($base_info);
            }

            if ($res['code'] == 1) {
                return $this->zbn_msg($res['msg'], 1, 'true', 1000, "''", "'reload_page()'");
            } else {
                return $this->zbn_msg($res['msg'] . $result['msg'], 2);
            }

        } else {
            $this->view->field_list = $model_info->get_admin_publish_fields([] , ['default' , 'reply_content']);
            return $this->view->fetch();
        }

    }

    public function delete($id){

        global $_W,$_GPC;
        $id = (int)$id;
        $model = set_model($this->sites_wechat_fans_group);
        /** @var Models $model_info */
        $model_info = $model->model_info;
        //$model_info = Models::get(['id' => $this->zwt_department]);
        $where['id'] =  $id;
        $where['site_id'] =  $_W['site']['id'];
        $detail = $model->where($where)->find();
        if($detail['wechat_tag_id'] <=2){
            return [
                'code' =>1 ,
                'msg' => "不可以删除系统保留标签"
            ];
        }
        $account_api = MhcmsWechatEngine::create($_W['account']);
        $tags = $account_api->fansTagDelete($detail['wechat_tag_id']);
        if(!is_error($tags)){
            $model->where($where)->delete();
            return [
                'code' =>1 ,
                'msg' => "ok"
            ];
        }



    }
    public function edit($id)
    {
        global $_W,$_GPC;
        $id = (int)$id;
        $model = set_model($this->sites_wechat_fans_group);
        /** @var Models $model_info */
        $model_info = $model->model_info;
        //$model_info = Models::get(['id' => $this->zwt_department]);
        $where = ['id' => $id];
        $detail = $model->where($where)->find();
        if ($this->isPost() && $model_info) {
            if (isset($_GPC['_form_manual'])) {
                //手动处理数据
                $data = $_GPC;
            } else {
                //自动获取data分组数据
                $data = input('post.data/a');//get the base info
            }
            // todo  process data input
            $account_api = MhcmsWechatEngine::create($_W['account']);
            $result = $account_api->fansTagEdit($detail['wechat_tag_id'], $data['group_name']);

            if(!is_error($result)){
                $model_info->edit_content($data, $where);
                $this->zbn_msg("ok");
            }

            $this->zbn_msg("error");
        } else {
            //todo auth
            //模板数据
            $this->view->list = $model_info->get_admin_publish_fields($detail);
            $this->view->model_info = $model_info;
            return $this->view->fetch();
        }
    }
}